### ISSUE TITLE
Create pwnmake builder images for all actively supported versions of Ubuntu

### ISSUE THREAD

**Issue by C0deH4cker** [C0deH4cker/PwnableHarness#21]
This is actually already done locally, just waiting to finish support for #10 & #14 and test everything at the same time before I merge it.

**Comment by nil0x42** [comment]
Hi @C0deH4cker , any news on it ? Could you publish current work on a dev branch so i can test it ? I'd really like to be able to use different versions of ubuntu

**Comment by C0deH4cker** [comment]
Hey @nil0x42, sorry I missed your comment! I'll try to push a dev branch (or get it working and merge to master) in the next week!

**Comment by C0deH4cker** [comment]
Work is ongoing in #27, but it's not ready or working just yet.

**Comment by C0deH4cker** [comment]
@nil0x42 PR #27 implements this, and I think it's ready to go. I just haven't fully tested all functionality yet to make sure I haven't broken something. Check `examples/BaseImage` for an example of this. All relevant Docker images have been pushed to Docker Hub: https://hub.docker.com/repository/docker/c0deh4cker/pwnableharness/tags.

**Comment by C0deH4cker** [comment]
Closing as complete, as #27 merged support for this into the `dev` branch. I'll eventually merge `dev` into `master` after completing testing.

**Comment by nil0x42** [comment]
Thank you very much !
